public class Utils  {
    
    static String IMAGENS[] = {"annie",
                        "bebe-stevens",
                        "butters-stotch",
                        "clyde-donovan",
                        "craig-tucker",
                        "david",
                        "eric-cartman",
                        "jimmy-valmer",
                        "kenny-mccormick",
                        "kyle-broflovski",
                        "pip-pirrup",
                        "stan-marsh",
                        "timmy-burch",
                        "token-black",
                        "wendy-testaburger",
                        "tweek-tweak",
                        "nichole",
                        "leroy-mullins",
                        "francis",
                        "esther",
                        "dog-poo-patuski",
                        "alter-egos-heidi-turner-w-hat"
                    };
   
   static String NOMES[] = {"Annie",
                        "Bebe Stevens",
                        "Butters Stotch",
                        "Clyde Donovan",
                        "Craig Tucker",
                        "David",
                        "Eric Cartman",
                        "Jimmy Valmer",
                        "Kenny McCormick",
                        "Kyle Broflovski",
                        "Pip Pirrup",
                        "Stan Marsh",
                        "Timmy Burch",
                        "Token Black",
                        "Wendy Testaburger",
                        "Tweek-Tweak",
                        "Nichole",
                        "Leroy Mullins",
                        "Francis",
                        "Esther",
                        "Dog-Poo-Patuski",
                        "Heidi"
                    };
}
